//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOHIEM
    {
        public int MASOBH { get; set; }
        public string TENBH { get; set; }
        public string MANV { get; set; }
        public string NOICAP { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public Nullable<double> SOTIENDONG { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
