//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOIDUONG
    {
        public int MABD { get; set; }
        public string MANV { get; set; }
        public string NOIBOIDUONG { get; set; }
        public System.DateTime THOIGIANDI { get; set; }
        public System.DateTime THOIGIANKETTHUC { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
