//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONGCANHAN
    {
        public string MANV { get; set; }
        public Nullable<double> LUONGCB { get; set; }
        public Nullable<double> HESO { get; set; }
        public Nullable<double> TIENPHUCAP { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
